-keep class * extends androidx.room.RoomDatabase
-keep @androidx.room.Entity class *
-dontwarn androidx.room.paging.**
-dontwarn org.apache.poi.**
-keep class org.apache.poi.** { *; }
-dontwarn com.itextpdf.**
-keep class com.itextpdf.** { *; }
